const DISC_PROFILES = {
  D: {
    name: "Dominância",
    description:
      "Pessoas com alta dominância são diretas, decisivas e focadas em resultados. Gostam de desafios e assumem riscos calculados.",
    characteristics: [
      "Orientado para resultados",
      "Decisivo e direto",
      "Gosta de desafios",
      "Assume riscos calculados",
      "Foca em objetivos",
      "Independente",
      "Competitivo",
      "Líder natural",
    ],
    strengths: [
      "Capacidade de tomar decisões rápidas",
      "Orientação para resultados",
      "Liderança natural",
      "Iniciativa e proatividade",
      "Coragem para assumir riscos",
      "Foco em objetivos",
      "Determinação e persistência",
    ],
    challenges: [
      "Pode ser impaciente com detalhes",
      "Tendência a ser muito direto",
      "Pode ignorar sentimentos dos outros",
      "Dificuldade em aceitar críticas",
      "Pode ser autoritário",
      "Impaciência com processos lentos",
    ],
  },
  I: {
    name: "Influência",
    description:
      "Pessoas com alta influência são entusiasmadas, expressivas e orientadas para pessoas. Gostam de interagir e inspirar outros.",
    characteristics: [
      "Entusiasmado e otimista",
      "Expressivo e comunicativo",
      "Orientado para pessoas",
      "Inspirador e motivador",
      "Flexível e adaptável",
      "Criativo e inovador",
      "Persuasivo",
      "Sociável",
    ],
    strengths: [
      "Habilidades de comunicação",
      "Capacidade de inspirar outros",
      "Otimismo e entusiasmo",
      "Flexibilidade e adaptabilidade",
      "Criatividade e inovação",
      "Networking e relacionamentos",
      "Persuasão e influência",
    ],
    challenges: [
      "Pode ser desorganizado",
      "Tendência a ser impulsivo",
      "Dificuldade com rotinas",
      "Pode ser superficial em análises",
      "Evita confrontos",
      "Pode ser inconsistente",
    ],
  },
  S: {
    name: "Estabilidade",
    description:
      "Pessoas com alta estabilidade são confiáveis, pacientes e orientadas para equipe. Valorizam harmonia e consistência.",
    characteristics: [
      "Confiável e leal",
      "Paciente e calmo",
      "Orientado para equipe",
      "Estável e consistente",
      "Bom ouvinte",
      "Cooperativo",
      "Empático",
      "Metódico",
    ],
    strengths: [
      "Confiabilidade e lealdade",
      "Paciência e estabilidade",
      "Habilidades de trabalho em equipe",
      "Capacidade de ouvir",
      "Empatia e compreensão",
      "Consistência no trabalho",
      "Mediação de conflitos",
    ],
    challenges: [
      "Resistência a mudanças",
      "Dificuldade em tomar decisões rápidas",
      "Pode ser passivo demais",
      "Evita confrontos",
      "Pode ser inflexível",
      "Dificuldade em dizer não",
    ],
  },
  C: {
    name: "Conformidade",
    description:
      "Pessoas com alta conformidade são analíticas, precisas e orientadas para qualidade. Valorizam excelência e precisão.",
    characteristics: [
      "Analítico e detalhista",
      "Preciso e exato",
      "Orientado para qualidade",
      "Sistemático e organizado",
      "Cauteloso e prudente",
      "Diplomático",
      "Perfeccionista",
      "Objetivo",
    ],
    strengths: [
      "Atenção aos detalhes",
      "Análise e pensamento crítico",
      "Qualidade e precisão",
      "Organização e sistematização",
      "Planejamento estratégico",
      "Diplomacia e tato",
      "Resolução de problemas",
    ],
    challenges: [
      "Pode ser perfeccionista demais",
      "Tendência a ser crítico",
      "Dificuldade com prazos apertados",
      "Pode ser inflexível",
      "Evita riscos",
      "Pode ser pessimista",
    ],
  },
};

module.exports = { DISC_PROFILES };
